micronaut:
    application:
        name: mongonaut
    metrics:
      enabled: true
      binders:
        jvm:
          enabled: false
    router:
      static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
      versioning:
        enabled: true
        default-version: 1
        header:
          enabled: true
          names:
            - 'X-API-VERSION'
            - 'Accept-Version'
jackson:
  bean-introspection-module: true
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
    reporter:
      flushInterval: 2000
      maxQueueSize: 200
mongodb:
    uri: mongodb://mongonaut:mongonaut1234@localhost:27017/mongonaut
endpoints:
  prometheus:
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  info:
    enabled: true
    sensitive: false
  health:
    sensitive: false
    enabled: true
    details-visible: ANONYMOUS
