apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongonaut.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/prometheus"
  labels:
    app.kubernetes.io/name: {{ include "mongonaut.name" . }}
    helm.sh/chart: {{ include "mongonaut.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mongonaut.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
