apiVersion: apps/v1
kind: Deployment
metadata:
  name: thorntail4-app
  labels:
    app: thorntail4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thorntail4-app
  template:
    metadata:
      labels:
        app: thorntail4-app
    spec:
      containers:
      - name: thorntail4-app
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        args: ["-XX:+UnlockExperimentalVMOptions"]
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thorntail4-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: thorntail4-app

